<?php

/**
 * Implementation of hook_hlp().
 */
function inline_comments_help() {
  $output = '';  //declare your output variable
  switch ($path) {
    case "admin/help#inline_comments":
      $output = '<p>'.  t("Inline comments is a view handler let you display  and make comments inline via ajax ") .'</p>';
      break;
  }
  return $output;
}


/**
 * Implementation hook_views_api
 */
function inline_comments_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'inline_comments') . '/inc',
  );
}


/**
  * Implementation of hook_menu()
  */

function inline_comments_menu() {
  $items['ajax/inline_comments/add_comments'] = array(
    'title' => t('Add Inline Comments'),
		'type' => MENU_CALLBACK,
		'file' => 'inc/ajax.inc',
    'page callback' => 'inline_comments_add_comments',
    'access arguments' => array('post comments'),
  );

	$items['ajax/inline_comments/get_comments/%'] = array(
    'title' => t('Get Inline Comments'),
		'type' => MENU_CALLBACK,
		'file' => 'inc/ajax.inc',
    'page callback' => 'inline_comments_get_comments',
    'access arguments' => array('access comments'),
  );
  $items['ajax/inline_comments/get_comment_form/%'] = array(
    'title' => t('Get Inline Comments'),
		'type' => MENU_CALLBACK,
		'file' => 'inc/ajax.inc',
    'page callback' => 'inline_comments_get_comment_form',
    'access arguments' => array('access comments'),
  );
  return $items;
}


//function inline_comments_theme_registry_alter(&$theme_registry) {
//  if (!empty($theme_registry['comment'])) {
//    $theme_registry['comment']['function'] = 'inline_comments_comment';
//  }
//}


function inline_comments_comment(&$comment) {
    unset($comment->subject);
}